In [26]:
import numpy
import sympy
from sympy.vector import *
from matplotlib import pyplot
from scipy.integrate import quad

In [27]:
from scipy.integrate import quad_vec

In [28]:
x, y, z, u1, u2, u3, v1, v2, v3, t = sympy.symbols('x y z u_1 u_2 u_3 v_1 v_2 v_3 t')

# جمع و ضرب های برداری

In [29]:
A = numpy.array([1,2,3]) #  بردار با مولفه های عدد
B = numpy.array([7,8,9]) # بردار با مولفه های عددی
U = sympy.Matrix([u1,u2,u3]) # مولفه های سمبولیک
V = sympy.Matrix([v1,v2,v3]) # مولفه های سمبولیک

In [30]:
A+B # جمع بردار

array([ 8, 10, 12])

In [31]:
2*(A+B) # ضرب همه مولفه های در عددی مثل 2

array([16, 20, 24])

In [32]:
U+V # جمع سمبولیک

Matrix([
[u_1 + v_1],
[u_2 + v_2],
[u_3 + v_3]])

In [33]:
2*(U+V) # ضرب 2 در همه ملفه های سمبولیک

Matrix([
[2*u_1 + 2*v_1],
[2*u_2 + 2*v_2],
[2*u_3 + 2*v_3]])

## ضرب داخلی بردارها

In [34]:
numpy.dot(A, B) # ضرب داخلی بردار های عددی

50

In [35]:
U.dot(V) # ضرب داخلی بردار ها به صورت سمبولیک

u_1*v_1 + u_2*v_2 + u_3*v_3

## ضرب خارجی بردارها

* || A x B || = ||A|| ||B|| Sinθ #رابطه ضرب خارجی بردار ها و زاویه بین آنها

In [36]:
numpy.cross(A,B) # ضرب خارجی بردارهای عددی

array([-6, 12, -6])

In [37]:
unit_direction_vector = numpy.cross(A,B) / numpy.linalg.norm(numpy.cross(A,B))
print(unit_direction_vector) # یکه کردن اندازه بردار با تقسیم مولفه ها به اندازه بردار

[-0.40824829  0.81649658 -0.40824829]


In [38]:
# اندازه حاصل ضرب  برداری
numpy.linalg.norm(numpy.cross(A,B))

14.696938456699069

In [39]:
U.cross(V) # ضرب خارجی بردارها به صورت سمبولیک

Matrix([
[ u_2*v_3 - u_3*v_2],
[-u_1*v_3 + u_3*v_1],
[ u_1*v_2 - u_2*v_1]])

In [40]:
U.norm() # اندازه بردار سمبولیک

sqrt(Abs(u_1)**2 + Abs(u_2)**2 + Abs(u_3)**2)

# مشتق تابع برداری

In [41]:
r = sympy.Matrix([3*t, sympy.sin(t), t**2])
r

Matrix([
[   3*t],
[sin(t)],
[  t**2]])

In [42]:
sympy.diff(r,t)

Matrix([
[     3],
[cos(t)],
[   2*t]])

پیدا کردن زاویه بین دو بردار #

acos : کد تابع arccos است


In [43]:
v = sympy.diff(r,t)
a = sympy.diff(v,t)
theta = sympy.acos(v.dot(a)/(v.norm()*a.norm())).simplify()

In [44]:
v

Matrix([
[     3],
[cos(t)],
[   2*t]])

In [45]:
a

Matrix([
[      0],
[-sin(t)],
[      2]])

In [46]:
theta

acos((4*t - sin(2*t)/2)/(sqrt(Abs(sin(t))**2 + 4)*sqrt(4*Abs(t)**2 + Abs(cos(t))**2 + 9)))

In [47]:
theta.subs(t,6).evalf()

0.251108015692338

## انتگرال تابع برداری

In [48]:
r = sympy.Matrix([sympy.exp(t)*sympy.cos(t), t**4, 1/(1+t**2)])
r

Matrix([
[exp(t)*cos(t)],
[         t**4],
[ 1/(t**2 + 1)]])

In [49]:
sympy.Integral(r).doit()

Matrix([
[exp(t)*sin(t)/2 + exp(t)*cos(t)/2],
[                           t**5/5],
[                          atan(t)]])

In [50]:
r = sympy.Matrix([sympy.exp(t**2)*sympy.cos(t)**3, sympy.exp(-t**4), 1/(3+t**2)])
r

Matrix([
[exp(t**2)*cos(t)**3],
[         exp(-t**4)],
[       1/(t**2 + 3)]])

Integrate from $t=0$ to $t=4$

In [51]:
r_num = sympy.lambdify([t], r)

In [52]:
quad_vec(r_num, 0, 4)[0]

array([[-4.83559254e+05],
       [ 9.06402477e-01],
       [ 6.70972506e-01]])


* محاسبه طول قوس

$$L = \int_a^b \sqrt{dx^2 + dy^2 + dz^2} = \int_a^b \sqrt{(dx/dt)^2 + (dy/dt)^2 + (dz/dt)^2 } dt $$

مثال:  $\left< 0, t, t^2 \right>$ from $t=0$ to $t=1$

In [55]:
# محاسبات سمبولیک
r = sympy.Matrix([0, t, t**2])
sympy.integrate(sympy.diff(r,t).norm(), (t,0,1))

asinh(2)/4 + sqrt(5)/2

مثال: $\left< e^t, \sin(t), t^4 \right>$ from $t=0$ to $t=1$

In [40]:
#محاسبات نمادی

r = sympy.Matrix([sympy.exp(t), sympy.sin(t), t**4])
r_num = sympy.lambdify([t], sympy.diff(r,t).norm())
quad(r_num, 0, 1)[0]

2.316977146444862

* بردار یکه مماسr: $\vec{T} = \frac{d\vec{r}}{dt}\frac{1}{|d\vec{r}/dt|} = \vec{v}/|\vec{v}|$ 
* انحناء: $\kappa = |\frac{d\vec{T}}{dt}|\frac{1}{|\vec{v}|}$
* $\vec{N} = \frac{d\vec{T}/dt}{|d\vec{T}/dt|}$ 


**Example** Find all these for $\vec{r}(t) = \left<a\cos(t)e^t, b\sin(t), ct\right>$

In [41]:
t, a, b, c = sympy.symbols('t a b c', pos=True, real=True)

Define the path

In [42]:
r = sympy.Matrix([a*sympy.cos(t)*sympy.exp(t), b*sympy.sin(t), c*t])
r

Matrix([
[a*exp(t)*cos(t)],
[       b*sin(t)],
[            c*t]])

Define the velocity vector $\vec{v}$ and speed $|\vec{v}|$

In [43]:
v = sympy.diff(r, t)
v_norm = v.norm()

Get $\vec{T}$, $\kappa$, and $\vec{N}$

In [44]:
T = v/v_norm
kappa = sympy.diff(T, t).norm()/v_norm
N = sympy.diff(T,t)/sympy.diff(T,t).norm()

مقداردهی به مقادیر مجهول

In [45]:
kappa.subs([(t,2),(a,3),(b,4),(c,5)]).evalf()

0.00775458595406284

In [46]:
N.subs([(t,2),(a,3),(b,4),(c,5)]).evalf()

Matrix([
[-0.152946073876551],
[-0.204518432770271],
[-0.966840063890063]])

## قاعده زنجیری

In [66]:
t = sympy.symbols('t')
x, y, z, w, v =sympy.symbols('x, y, z w v', cls=sympy.Function)

* فرض کنیم $x$, $y$, و $z$ تابعی از $t$ هستند
* $w$ تابعی از $x$, $y$, و $z$ است. i.e $w=w(x,y,z)$

 $dw/dt =؟$

In [49]:
x = x(t)
y = y(t)
z = z(t)
w = w(x, y, z)

In [50]:
sympy.diff(w,t)

Derivative(w(x(t), y(t), z(t)), x(t))*Derivative(x(t), t) + Derivative(w(x(t), y(t), z(t)), y(t))*Derivative(y(t), t) + Derivative(w(x(t), y(t), z(t)), z(t))*Derivative(z(t), t)

In [51]:
w1 = x**2+sympy.exp(y)*sympy.sin(z)
sympy.diff(w1,t).subs([(x, sympy.sin(t)),
                    (y, sympy.cos(t)),
                    (z, t**2)]).doit()

2*t*exp(cos(t))*cos(t**2) - exp(cos(t))*sin(t)*sin(t**2) + 2*sin(t)*cos(t)

## روش ضرایب لاگرانژ یا بهینه سازی مقید

مینیمم $f(x,y,z)$ را با قید $g(x,y,z)=0$ بیابید

* باید این دو معادله را حل کنیمs $\nabla f = \lambda \nabla g$ و $g(x,y,z)=0$

**مثال**:  $g(x,y,z)= 4x^2 + y^2 + 4z^2 = 16$ باقید $f(x,y,z)=8x^2+4yz-16z+600$. 

In [ ]:
C = CoordSys3D('')

In [ ]:
lam = sympy.symbols('\lambda')
g = 4*C.x**2 + C.y**2 + 4*C.z**2 - 16
f = 8*C.x**2 + 4*C.y*C.z-16*C.z+600
eq1 = gradient(f)-lam*gradient(g)
eq1 = eq1.to_matrix(C)
eq2 = g
sols = sympy.solve([eq1, eq2])
sols

[{.x: -4/3, .y: -4/3, .z: -4/3, \lambda: 2},
 {.x: 0, .y: -2, .z: -sqrt(3), \lambda: sqrt(3)},
 {.x: 0, .y: -2, .z: sqrt(3), \lambda: -sqrt(3)},
 {.x: 0, .y: 4, .z: 0, \lambda: 0},
 {.x: 4/3, .y: -4/3, .z: -4/3, \lambda: 2}]

In [ ]:
for sol in sols:
    print(f.subs(sol).evalf())

642.666666666667
641.569219381653
558.430780618347
600.000000000000
642.666666666667


# انتگرال چندگانه

In rare cases these can be done symbolically:

$$\int_0^1 \int_0^{1-x^2} \int_3^{4-x^2-y^2} xdzdydx$$

In [ ]:
x, y, z = sympy.symbols('x, y, z')
f = x
sympy.integrate(f, (z, 3, 4-x**2-y**2), (y, 0, 1-x**2), (x, 0, 1))

1/8

مثال:

$$\int_0^1 \int_0^{1-x^2} \int_3^{4-x^2-y^2} xe^{-y}\cos(z)dzdydx$$

In [ ]:
from scipy.integrate import tplquad
f = lambda z, y, x: x*np.exp(-y)*np.cos(z)
tplquad(f, 0, 1,
        lambda x: 0, lambda x: 1-x**2,
        lambda x, y: 3, lambda x, y: 4-x**2-y**2)[0]

-0.09109526451447894

## انتگرال خط



$$\int_C f(x,y,z) ds = \int_a^b f(g(t), h(t), k(t))|d\vec{r}/dt|dt$$

In [ ]:
t = sympy.symbols('t', real=True)
x, y, z, f = sympy.symbols('x y z f', cls=sympy.Function, real=True)
x = x(t)
y = y(t)
z = z(t)
r = sympy.Matrix([x, y, z])
f = f(x,y,z)

In [ ]:
integrand = f*sympy.diff(r,t).norm()
integrand

sqrt(Abs(Derivative(x(t), t))**2 + Abs(Derivative(y(t), t))**2 + Abs(Derivative(z(t), t))**2)*f(x(t), y(t), z(t))

فرض کنید: 
* $\vec{r}(t) = \left<\cos(t), \sin(t), t \right>$ 
* $f(x,y,z)=2xy+\sqrt{z}$ 
* $t=0$ تا $t=2\pi$. 

In [ ]:
integrand1 = integrand.subs([(f, 2*x*y+sympy.sqrt(z)),
                            (x, sympy.cos(t)),
                            (y, sympy.sin(t)),
                            (z, t)]).doit().simplify()
sympy.integrate(integrand1, (t, 0, 2*sympy.pi))

sqrt(2)/2 + sqrt(2)*(-1/2 + 4*sqrt(2)*pi**(3/2)/3)

فرض کنید:

* $\vec{r}(t) = \left<3\cos(t), 2\sin(t), e^{t/4} \right>$ 
* $f(x,y,z)=2xy+\sqrt{z}$ 
* $t=0$ تا $t=2\pi$.

In [ ]:
integrand2 = integrand.subs([(f, 2*x*y+sympy.sqrt(z)),
                            (x, 3*sympy.cos(t)),
                            (y, sympy.sin(t)),
                            (z, sympy.exp(t/4))]).doit().simplify()
# Won't Run!
#sympy.integrate(integrand2, (t, 0, 2*sympy.pi))

In [ ]:
integrand2

(exp(t/8) + 3*sin(2*t))*sqrt(exp(t/2) + 128*sin(t)**2 + 16)/4

In [ ]:
integrand2_num = sympy.lambdify([t], integrand2)
quad(integrand2_num, 0, 2*np.pi)[0]

21.055300456759795



$$\int_C \vec{F}(x,y,z) \cdot d\vec{r} = \int_a^b\vec{F}(g(t), h(t), k(t)) \cdot \frac{d\vec{r}}{dt} dt$$

In [ ]:
t = sympy.symbols('t', real=True)
x, y, z, F1, F2, F3 = sympy.symbols('x y z F_1, F_2, F_3', cls=sympy.Function, real=True)
x = x(t)
y = y(t)
z = z(t)
F1 = F1(x,y,z)
F2 = F2(x,y,z)
F3 = F3(x,y,z)
r = sympy.Matrix([x, y, z])
F = sympy.Matrix([F1, F2, F3])

In [ ]:
integrand = F.dot(sympy.diff(r,t))
integrand

F_1(x(t), y(t), z(t))*Derivative(x(t), t) + F_2(x(t), y(t), z(t))*Derivative(y(t), t) + F_3(x(t), y(t), z(t))*Derivative(z(t), t)

فرض کنید: $\vec{F} = \left< \sqrt{z}, -2x, \sqrt{y}\right>$ و $\vec{r}(t) = \left<t, t^2, t^4 \right>$ از $t=0$ تا $t=1$

In [ ]:
integrand1 = integrand.subs([(F1, sympy.sqrt(z)),
                             (F2, -2*x),
                             (F3, sympy.sqrt(y)),
                             (x, t),
                             (y, t**2),
                             (z, t**4)]).doit().simplify()
sympy.integrate(integrand1, (t, 0, 1))

-1/5



فرض کنید:  $\vec{F} = \left< \sqrt{|z|}, -2x, \sqrt{|y|}\right>$ و $\vec{r}(t) = \left<3\cos^2(t), t^2, 2\sin(t) \right>$ از $t=0$ تا $t=2\pi$

In [ ]:
integrand2 = integrand.subs([(F1, sympy.sqrt(sympy.Abs(z))),
                             (F2, -2*x),
                             (F3, sympy.sqrt(sympy.Abs(y))),
                             (x, 3*sympy.cos(t)**2),
                             (y, t**2),
                             (z, 2*sympy.sin(t))]).doit().simplify()
# Won't Run
#sympy.integrate(integrand2, (t, 0, 2*sympy.pi))

In [ ]:
integrand2

2*(-6*t*cos(t) - 3*sqrt(2)*sin(t)*sqrt(Abs(sin(t))) + Abs(t))*cos(t)

In [ ]:
integrand2_num = sympy.lambdify([t], integrand2)
quad(integrand2_num, 0, 2*np.pi)[0]

-118.4352528130723

## انتگرال سطح

 $\vec{r}(u,v)$ داده شده 

$$A = \iint_S \left| \frac{d\vec{r}}{du} \times \frac{d\vec{r}}{dv} \right| du dv$$
داریم:

$$\iint_S G(\vec{r}(u,v)) \left| \frac{d\vec{r}}{du} \times \frac{d\vec{r}}{dv} \right| du dv$$

In [ ]:
rho, the = sympy.symbols(r'\rho \theta',pos=True, real=True)
x, y, z, G = sympy.symbols('x y z G', cls=sympy.Function, real=True)
x = x(rho, the)
y = y(rho, the)
z = z(rho, the)
G = G(x,y,z)
r = sympy.Matrix([x, y, z])

In [ ]:
integrand = G*sympy.diff(r,rho).cross(sympy.diff(r,the)).norm()
integrand

sqrt(Abs(Derivative(x(\rho, \theta), \rho)*Derivative(y(\rho, \theta), \theta) - Derivative(x(\rho, \theta), \theta)*Derivative(y(\rho, \theta), \rho))**2 + Abs(Derivative(x(\rho, \theta), \rho)*Derivative(z(\rho, \theta), \theta) - Derivative(x(\rho, \theta), \theta)*Derivative(z(\rho, \theta), \rho))**2 + Abs(Derivative(y(\rho, \theta), \rho)*Derivative(z(\rho, \theta), \theta) - Derivative(y(\rho, \theta), \theta)*Derivative(z(\rho, \theta), \rho))**2)*G(x(\rho, \theta), y(\rho, \theta), z(\rho, \theta))

In [ ]:
integrand1 = integrand.subs([(G, x**2+y**2),
                             (x, rho*sympy.cos(the)),
                             (y, rho*sympy.sin(the)),
                             (z, rho**2)]).doit().simplify()
integrand1

\rho**2*sqrt(4*\rho**2 + 1)*Abs(\rho)

In [ ]:
sympy.integrate(integrand1, (the, 0, 2*sympy.pi), (rho, 0, 1))

pi/60 + 5*sqrt(5)*pi/12

## Surface Integrals (Vector)

انتگرال سطح تابع برداری $\vec{G}(\vec{r})$ به صورت :

$$\iint_S \vec{G}(\vec{r}(u,v)) \cdot \left(\frac{d\vec{r}}{du} \times \frac{d\vec{r}}{dv}\right) du dv$$


In [ ]:
rho, the = sympy.symbols(r'\rho \theta',pos=True, real=True)
x, y, z, G1, G2, G3 = sympy.symbols('x y z G_1, G_2, G_3', cls=sympy.Function, real=True)
x = x(rho, the)
y = y(rho, the)
z = z(rho, the)
G1 = G1(x,y,z)
G2 = G2(x,y,z)
G3 = G3(x,y,z)
r = sympy.Matrix([x, y, z])
G = sympy.Matrix([G1, G2, G3])

In [ ]:
integrand = G.dot(sympy.diff(r,rho).cross(sympy.diff(r,the)))
integrand

(Derivative(x(\rho, \theta), \rho)*Derivative(y(\rho, \theta), \theta) - Derivative(x(\rho, \theta), \theta)*Derivative(y(\rho, \theta), \rho))*G_3(x(\rho, \theta), y(\rho, \theta), z(\rho, \theta)) + (-Derivative(x(\rho, \theta), \rho)*Derivative(z(\rho, \theta), \theta) + Derivative(x(\rho, \theta), \theta)*Derivative(z(\rho, \theta), \rho))*G_2(x(\rho, \theta), y(\rho, \theta), z(\rho, \theta)) + (Derivative(y(\rho, \theta), \rho)*Derivative(z(\rho, \theta), \theta) - Derivative(y(\rho, \theta), \theta)*Derivative(z(\rho, \theta), \rho))*G_1(x(\rho, \theta), y(\rho, \theta), z(\rho, \theta))

In [ ]:
integrand1 = integrand.subs([(G1, y**2),
                             (G2, z),
                             (G3, 0),
                             (x, rho*sympy.cos(the)),
                             (y, rho*sympy.sin(the)),
                             (z, rho**2)]).doit().simplify()
integrand1

-2*\rho**4*(sin(2*\theta)/2 + 1)*sin(\theta)

In [ ]:
sympy.integrate(integrand1, (the, 0, sympy.pi), (rho, 0, 1))

-4/5